blank_issues_enabled: false
contact_links:
  - name: Questions and Discussions
    url: https://github.com/bab3l/terraform-provider-netbox/discussions
    about: Please use Discussions for general questions.